##########################################################
##########     Object Information(goal)   ######################

moveit_msgs/CollisionObject object

---
##########################################################
##########     Pickup Result (result)   ######################

std_msgs/Bool success

---

##########################################################
##########     Pickup Feedback (feedback)   ######################

std_msgs/Bool success

