##########################################################
##########     Object Information(goal)   ######################

uint32 object_class
string object_name

geometry_msgs/PoseStamped[] destinations

string support_surface
---
##########################################################
##########     Pickup Result (result)   ######################

std_msgs/Bool success

string cob_pick_error_string

---

##########################################################
##########     Pickup Feedback (feedback)   ######################

std_msgs/Bool success

string cob_pick_error_string
