# type of the collision_object (SPHERE, CYLINDER, BOX, MESH, URDF, DETECT)
byte SPHERE=0
byte BOX=1
byte CYLINDER=2
byte MESH=3
byte URDF=4
byte DETECT=5
byte type

# id of the object
string id

# add, remove
string operation

geometry_msgs/PoseStamped pose

# depending on type
float64[] dimensions

# padding for collision object
float32 padding

# filename of mesh or urdf
string filename

# scale factor (for mesh type only)
geometry_msgs/Vector3 scale

# collision_object will be attached to this link
string attach_link
# touch_links are allowed to be in collision with attached_object
string[] touch_links

---
bool success
string error_message
