multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link

groups:
  - name: arm
    base_link: base_link
    tip_link: arm_7_link

# The default padding to assign to agent links for the purposes
# of environmental collision checking
default_robot_padding: .08

# The default padding to assign to collision objects and attached
# collision objects for the purposes of filtering them from the
# collision map
#default_object_padding: .03


default_collision_operations:
  - object1: base_link
    object2: arm_0_link
    operation: disable  # Adjacent in collision
  - object1: arm_0_link
    object2: arm_1_link
    operation: disable  # Adjacent in collision
  - object1: arm_1_link
    object2: arm_2_link
    operation: disable  # Adjacent in collision
  - object1: arm_2_link
    object2: arm_3_link
    operation: disable  # Adjacent in collision
  - object1: arm_3_link
    object2: arm_4_link
    operation: disable  # Adjacent in collision
  - object1: arm_4_link
    object2: arm_5_link
    operation: disable  # Adjacent in collision
  - object1: arm_5_link
    object2: arm_6_link
    operation: disable  # Adjacent in collision
  - object1: arm_6_link
    object2: arm_7_link
    operation: disable  # Adjacent in collision
  - object1: arm_7_link
    object2: sdh_palm_link
    operation: disable  # Adjacent in collision
  - object1: sdh_palm_link
    object2: sdh_finger_21_link
    operation: disable  # Adjacent in collision
  - object1: sdh_finger_21_link
    object2: sdh_finger_22_link
    operation: disable  # Adjacent in collision
  - object1: sdh_finger_22_link
    object2: sdh_finger_23_link
    operation: disable  # Adjacent in collision
  - object1: sdh_palm_link
    object2: sdh_grasp_link
    operation: disable  # Adjacent in collision
  - object1: sdh_palm_link
    object2: sdh_finger_11_link
    operation: disable  # Adjacent in collision
  - object1: sdh_finger_11_link
    object2: sdh_finger_12_link
    operation: disable  # Adjacent in collision
  - object1: sdh_finger_12_link
    object2: sdh_finger_13_link
    operation: disable  # Adjacent in collision
  - object1: sdh_palm_link
    object2: sdh_thumb_1_link
    operation: disable  # Adjacent in collision
  - object1: sdh_thumb_1_link
    object2: sdh_thumb_2_link
    operation: disable  # Adjacent in collision
  - object1: sdh_thumb_2_link
    object2: sdh_thumb_3_link
    operation: disable  # Adjacent in collision
  - object1: sdh_palm_link
    object2: sdh_tip_link
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: tof_link
    operation: disable  # Adjacent in collision
  - object1: tof_link
    object2: tof_frame
    operation: disable  # Adjacent in collision
  - object1: arm_0_link
    object2: arm_2_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: arm_3_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: arm_4_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: arm_5_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: arm_6_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: arm_7_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: sdh_finger_11_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: sdh_finger_12_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: sdh_finger_13_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: sdh_finger_21_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: sdh_finger_23_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: sdh_thumb_1_link
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: tof_frame
    operation: disable  # Never in collision
  - object1: arm_0_link
    object2: tof_link
    operation: disable  # Never in collision
  - object1: arm_1_link
    object2: arm_3_link
    operation: disable  # Never in collision
  - object1: arm_1_link
    object2: arm_4_link
    operation: disable  # Never in collision
  - object1: arm_1_link
    object2: arm_5_link
    operation: disable  # Never in collision
  - object1: arm_1_link
    object2: arm_6_link
    operation: disable  # Never in collision
  - object1: arm_1_link
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_1_link
    object2: tof_frame
    operation: disable  # Never in collision
  - object1: arm_1_link
    object2: tof_link
    operation: disable  # Never in collision
  - object1: arm_2_link
    object2: arm_4_link
    operation: disable  # Never in collision
  - object1: arm_2_link
    object2: arm_5_link
    operation: disable  # Never in collision
  - object1: arm_2_link
    object2: arm_6_link
    operation: disable  # Never in collision
  - object1: arm_2_link
    object2: arm_7_link
    operation: disable  # Never in collision
  - object1: arm_2_link
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_2_link
    object2: sdh_palm_link
    operation: disable  # Never in collision
  - object1: arm_2_link
    object2: tof_frame
    operation: disable  # Never in collision
  - object1: arm_2_link
    object2: tof_link
    operation: disable  # Never in collision
  - object1: arm_3_link
    object2: arm_5_link
    operation: disable  # Never in collision
  - object1: arm_3_link
    object2: arm_6_link
    operation: disable  # Never in collision
  - object1: arm_3_link
    object2: arm_7_link
    operation: disable  # Never in collision
  - object1: arm_3_link
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_3_link
    object2: sdh_thumb_1_link
    operation: disable  # Never in collision
  - object1: arm_3_link
    object2: tof_frame
    operation: disable  # Never in collision
  - object1: arm_3_link
    object2: tof_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: arm_6_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: arm_7_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: sdh_finger_11_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: sdh_finger_12_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: sdh_finger_13_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: sdh_finger_21_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: sdh_finger_22_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: sdh_finger_23_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: sdh_palm_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: sdh_thumb_1_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: sdh_thumb_2_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: sdh_thumb_3_link
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: tof_frame
    operation: disable  # Never in collision
  - object1: arm_4_link
    object2: tof_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: arm_7_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: sdh_finger_11_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: sdh_finger_12_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: sdh_finger_13_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: sdh_finger_21_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: sdh_finger_22_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: sdh_finger_23_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: sdh_palm_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: sdh_thumb_1_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: sdh_thumb_2_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: sdh_thumb_3_link
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: tof_frame
    operation: disable  # Never in collision
  - object1: arm_5_link
    object2: tof_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: sdh_finger_11_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: sdh_finger_12_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: sdh_finger_13_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: sdh_finger_21_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: sdh_finger_22_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: sdh_finger_23_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: sdh_palm_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: sdh_thumb_1_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: sdh_thumb_2_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: sdh_thumb_3_link
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: tof_frame
    operation: disable  # Never in collision
  - object1: arm_6_link
    object2: tof_link
    operation: disable  # Never in collision
  - object1: arm_7_link
    object2: sdh_finger_11_link
    operation: disable  # Never in collision
  - object1: arm_7_link
    object2: sdh_finger_12_link
    operation: disable  # Never in collision
  - object1: arm_7_link
    object2: sdh_finger_13_link
    operation: disable  # Never in collision
  - object1: arm_7_link
    object2: sdh_finger_21_link
    operation: disable  # Never in collision
  - object1: arm_7_link
    object2: sdh_finger_22_link
    operation: disable  # Never in collision
  - object1: arm_7_link
    object2: sdh_finger_23_link
    operation: disable  # Never in collision
  - object1: arm_7_link
    object2: sdh_thumb_1_link
    operation: disable  # Never in collision
  - object1: arm_7_link
    object2: sdh_thumb_2_link
    operation: disable  # Never in collision
  - object1: arm_7_link
    object2: sdh_thumb_3_link
    operation: disable  # Never in collision
  - object1: base_link
    object2: tof_frame
    operation: disable  # Never in collision
  - object1: sdh_finger_11_link
    object2: sdh_finger_13_link
    operation: disable  # Never in collision
  - object1: sdh_finger_11_link
    object2: sdh_finger_21_link
    operation: disable  # Never in collision
  - object1: sdh_finger_11_link
    object2: sdh_thumb_1_link
    operation: disable  # Never in collision
  - object1: sdh_finger_12_link
    object2: sdh_palm_link
    operation: disable  # Never in collision
  - object1: sdh_finger_21_link
    object2: sdh_finger_23_link
    operation: disable  # Never in collision
  - object1: sdh_finger_21_link
    object2: sdh_thumb_1_link
    operation: disable  # Never in collision
  - object1: sdh_finger_21_link
    object2: sdh_thumb_3_link
    operation: disable  # Never in collision
  - object1: sdh_finger_22_link
    object2: sdh_palm_link
    operation: disable  # Never in collision
  - object1: sdh_palm_link
    object2: sdh_thumb_2_link
    operation: disable  # Never in collision
  - object1: sdh_thumb_1_link
    object2: sdh_thumb_3_link
    operation: disable  # Never in collision
  - object1: sdh_thumb_1_link
    object2: tof_frame
    operation: disable  # Never in collision