skip_links:
 - base_footprint
 - fl_caster_rotation_link
 - fl_caster_r_wheel_link
 - b_caster_rotation_link
 - b_caster_r_wheel_link
 - fr_caster_rotation_link
 - fr_caster_r_wheel_link
 - base_laser_front_link
 - base_laser_left_link
 - base_laser_right_link
 - torso_base_link
 - torso_1_link
 - torso_2_link
 - torso_center_link
 - torso_cam3d_left_link
 - torso_cam3d_left_frame
 - torso_cam3d_right_link
 - torso_cam3d_right_frame
 - torso_cam3d_down_link
 - head_base_link
 - head_1_link
 - head_2_link
 - head_center_link
 - head_cam_link
 - head_cam_frame
 - sensorring_base_link
 - sensorring_link
 - sensorring_cam3d_front_link
 - sensorring_cam3d_back_link
 - sensorring_cam3d_back_frame
 - gripper_right_base_link
 - gripper_right_grasp_link
 - gripper_right_camera_link
 - gripper_left_base_link
 - gripper_left_grasp_link
 - gripper_left_camera_link
