joint_limits:
  arm_1_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_2_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_3_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_4_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_5_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_6_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_7_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
